/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/matches/{matchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Match header, score and stats */
        get: operations["getMatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{matchId}/flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Flow and per-minute history */
        get: operations["getMatchFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{matchId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Match timeline, newest first */
        get: operations["getMatchEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{matchId}/insight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** AI output — explanation, outcome prediction, fan sentiment */
        get: operations["getMatchInsight"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws/matches/{matchId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket — live updates for one match
         * @description Upgrades to WebSocket. The server pushes WsMessage frames (JSON).
         *     On a gap in `seq` the client refetches the REST resources.
         */
        get: operations["streamMatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 Problem Details */
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description Shown in the error card ("req 7f3a91") */
            requestId?: string;
        };
        /** @enum {string} */
        Side: "home" | "away";
        Team: {
            id: string;
            /** @description Three-letter code, e.g. MCI */
            code: string;
            name: string;
        };
        Score: {
            home: number;
            away: number;
        };
        Match: {
            id: string;
            /** @enum {string} */
            status: "scheduled" | "live" | "halftime" | "finished" | "postponed";
            /** Format: date-time */
            kickoffAt: string;
            competition: {
                id: string;
                name: string;
                round?: string;
            };
            venue?: {
                name?: string;
                city?: string;
            };
            home: components["schemas"]["Team"];
            away: components["schemas"]["Team"];
            score: components["schemas"]["Score"];
            halftimeScore?: components["schemas"]["Score"] | null;
            clock: components["schemas"]["Clock"];
            stats: components["schemas"]["StatRow"][];
        };
        Clock: {
            /** @description Match time in seconds (72:14 → 4334) */
            elapsedSeconds: number;
            /** @enum {string} */
            period: "first_half" | "second_half" | "extra_time" | "penalties";
            /**
             * Format: date-time
             * @description Server time when elapsedSeconds was measured; the client keeps ticking from here
             */
            observedAt: string;
        };
        StatRow: {
            /** @description possession, shots, shots_on_target, xg, key_passes, pressure_tackles */
            key: string;
            home: number;
            away: number;
        };
        FlowValues: {
            home: number;
            away: number;
        };
        FlowPoint: {
            minute: number;
            home: number;
            away: number;
        };
        FlowSeries: {
            matchId: string;
            current: components["schemas"]["FlowValues"];
            /** @description Flow now minus Flow 10 match minutes ago */
            delta10: {
                home: number;
                away: number;
            };
            /** @description One point per played minute. The client derives the wave and 1/5/15 windows. */
            points: components["schemas"]["FlowPoint"][];
            /** Format: date-time */
            updatedAt: string;
        };
        MatchEvent: {
            id: string;
            /** @enum {string} */
            type: "goal" | "shot_on_target" | "shot_off_target" | "shot_blocked" | "corner" | "yellow_card" | "red_card" | "substitution" | "foul" | "offside" | "take_on" | "halftime" | "fulltime";
            side: components["schemas"]["Side"] | null;
            minute: number;
            /** @description 45+2 → minute 45, addedTime 2 */
            addedTime?: number | null;
            player?: components["schemas"]["PersonRef"];
            assist?: components["schemas"]["PersonRef"];
            xG?: number | null;
            /** @description 0–100, attacking left to right */
            position?: {
                x?: number;
                y?: number;
            };
            scoreAfter?: components["schemas"]["Score"];
            /** @description The event's weight w(e) from docs/FLOW.md */
            flowImpact?: number | null;
        };
        PersonRef: {
            id: string;
            name: string;
        } | null;
        EventList: {
            items: components["schemas"]["MatchEvent"][];
        };
        Probabilities: {
            home: number;
            draw: number;
            away: number;
        };
        Insight: {
            matchId: string;
            /** @description Null until the Explainability agent answers */
            explanation?: components["schemas"]["Explanation"] | null;
            prediction: {
                current: components["schemas"]["Probabilities"];
                preMatch: components["schemas"]["Probabilities"];
                /** @example LightGBM v0.3 */
                model: string;
            };
            sentiment?: components["schemas"]["Sentiment"] | null;
        };
        Explanation: {
            title: string;
            text: string;
            factors: {
                label: string;
                impact: number;
            }[];
            /** Format: date-time */
            generatedAt: string;
        };
        Sentiment: {
            messagesPerMinute: number;
            home: components["schemas"]["FanMood"];
            away: components["schemas"]["FanMood"];
        };
        FanMood: {
            score: number;
            /** @example эйфория */
            mood: string;
        };
        WsMessage: components["schemas"]["WsMatchEvent"] | components["schemas"]["WsFlowUpdate"] | components["schemas"]["WsPredictionUpdate"] | components["schemas"]["WsInsightUpdate"];
        WsEnvelope: {
            type: string;
            matchId: string;
            /** @description Increases by 1 per message within a match; a gap means messages were lost */
            seq: number;
            /** Format: date-time */
            sentAt: string;
        };
        WsMatchEvent: components["schemas"]["WsEnvelope"] & {
            /** @constant */
            type?: "match.event";
            data: components["schemas"]["MatchEvent"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "match.event";
        };
        WsFlowUpdate: components["schemas"]["WsEnvelope"] & {
            /** @constant */
            type?: "flow.update";
            data: {
                current: components["schemas"]["FlowValues"];
                delta10: components["schemas"]["FlowValues"];
                point: components["schemas"]["FlowPoint"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "flow.update";
        };
        WsPredictionUpdate: components["schemas"]["WsEnvelope"] & {
            /** @constant */
            type?: "prediction.update";
            data: components["schemas"]["Probabilities"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "prediction.update";
        };
        WsInsightUpdate: components["schemas"]["WsEnvelope"] & {
            /** @constant */
            type?: "insight.update";
            data: components["schemas"]["Explanation"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "insight.update";
        };
    };
    responses: {
        /** @description Access token missing or expired */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Match not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                /** @description Seconds to wait */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unexpected error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @example m_01J8ZQ4T7K */
        MatchId: string;
    };
    requestBodies: never;
    headers: {
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example m_01J8ZQ4T7K */
                matchId: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            /** @description Not modified (If-None-Match matched) */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["Error"];
        };
    };
    getMatchFlow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example m_01J8ZQ4T7K */
                matchId: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowSeries"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["Error"];
        };
    };
    getMatchEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example m_01J8ZQ4T7K */
                matchId: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["Error"];
        };
    };
    getMatchInsight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example m_01J8ZQ4T7K */
                matchId: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Insight"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            default: components["responses"]["Error"];
        };
    };
    streamMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example m_01J8ZQ4T7K */
                matchId: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching protocols. Frames follow the WsMessage schema. */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WsMessage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
