import type { components } from './schema'

type Schemas = components['schemas']

export type WsMessage = Schemas['WsMessage']
export type MatchEvent = Schemas['MatchEvent']
export type FlowValues = Schemas['FlowValues']
export type FlowPoint = Schemas['FlowPoint']
export type Match = Schemas['Match']
export type FlowSeries = Schemas['FlowSeries']
export type EventList = Schemas['EventList']
export type Score = Schemas['Score']
export type Side = Schemas['Side']
export type Problem = Schemas['Problem']
export type StatRow = Schemas['StatRow']
export type FlowFactor = Schemas['FlowFactor']
export type Insight = Schemas['Insight']
export type Prediction = Schemas['Prediction']
export type Probabilities = Schemas['Probabilities']
export type Simulation = Schemas['Simulation']
export type SimulationRequest = Schemas['SimulationRequest']
export type SimulatedRed = Schemas['SimulatedRed']
export type MatchList = Schemas['MatchList']
export type MatchSummary = Schemas['MatchSummary']
export type Analysis = Schemas['Explanation'] // the AI agent's text; explain ts builds the one from Flow
